services:
  blogapp:
    image: blogapp-backend  # Uses an existing Docker image named "blogapp-backend".
    build:
      context: .  # The Dockerfile is located in the current directory.
      dockerfile: Dockerfile  # Specifies the Dockerfile for building the image.
    ports:
      - "8085:8085"  # Maps port 8084 of the container to port 8084 on the host.
    environment:
      - TZ=Asia/Kathmandu
    env_file:
      - .env
    networks:
      - dev_network
    depends_on:
      - redis-blogapp
      - minio-dev
      - postgres-dev

  postgres-dev:
    image: postgres:15.10
    container_name: postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"  # Maps port 5434 on the host machine to the default PostgreSQL port (5432) inside the container.
    networks:
      - dev_network

  redis-blogapp:
    image: redis:7.0-alpine
    container_name: redis-blogapp
    ports:
      - "6379:6379"
    networks:
      - dev_network

  minio-dev:
    image: minio/minio
    container_name: minio-blogapp-dev
    ports:
      - "${MINIO_PORT_EXPOSE:-9000}:9000"
      - "${MINIO_WEB_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  minio_data: