services:
  blogapp:
    image: blogapp-backend  # Uses an existing Docker image named "blogapp-backend".
    build:
      context: .  # The Dockerfile is located in the current directory.
      dockerfile: Dockerfile  # Specifies the Dockerfile for building the image.
    ports:
      - "8085:8085"  # Maps port 8084 of the container to port 8084 on the host.
    environment:
      - TZ=Asia/Kathmandu
    env_file:
      - .env
    networks:
      - dev_network
    depends_on:
      - redis-blogapp
      - localstack
      - postgres-dev

  postgres-dev:
    image: postgres:15.10
    container_name: postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"  # Maps port 5434 on the host machine to the default PostgreSQL port (5432) inside the container.
    networks:
      - dev_network

  redis-blogapp:
    image: redis:7.0-alpine
    container_name: redis-blogapp
    ports:
      - "6379:6379"
    networks:
      - dev_network

  localstack:
    image: localstack/localstack:latest  # Uses the latest version of LocalStack.
    container_name: localstack  # Assigns a fixed name to the container.
    ports:
      - "4566:4566"
    #    ports:
    #      - "4566:4566" # Maps the LocalStack API gateway port.
    #      - "4572:4572" # Maps the S3 service port.
    environment:
      - SERVICES=s3  # Enables only the S3 service in LocalStack.
      - DEFAULT_REGION=us-west-2  # Sets the AWS region for the local environment.
    volumes:
      - ./localstack/s3:/docker-entrypoint-initaws.d  # Mounts a local directory to persist data across container restarts.
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge